// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProyectoMancariBlue.Models;

#nullable disable

namespace ProyectoMancariBlue.Migrations
{
    [DbContext(typeof(DBContext))]
    [Migration("20240608061114_firstMigration")]
    partial class firstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_0900_ai_ci")
                .HasAnnotation("ProductVersion", "6.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");

            modelBuilder.Entity("ProyectoMancariBlue.Models.Empleado", b =>
                {
                    b.Property<int>("IdEmpleado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idEmpleado");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("apellido");

                    b.Property<byte[]>("Contrasena")
                        .IsRequired()
                        .HasColumnType("blob")
                        .HasColumnName("contrasena");

                    b.Property<string>("CorreoElectronico")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("correoElectronico");

                    b.Property<int>("IdEstadoEmpleado")
                        .HasColumnType("int")
                        .HasColumnName("idEstadoEmpleado");

                    b.Property<int>("IdRolEmpleado")
                        .HasColumnType("int")
                        .HasColumnName("idRolEmpleado");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nombre");

                    b.Property<decimal>("Telefono")
                        .HasPrecision(8)
                        .HasColumnType("decimal(8)")
                        .HasColumnName("telefono");

                    b.HasKey("IdEmpleado")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "CorreoElectronico" }, "correoElectronico")
                        .IsUnique();

                    b.HasIndex(new[] { "IdEstadoEmpleado" }, "idEstadoEmpleado");

                    b.HasIndex(new[] { "IdRolEmpleado" }, "idRolEmpleado");

                    b.HasIndex(new[] { "Telefono" }, "telefono")
                        .IsUnique();

                    b.ToTable("empleado", (string)null);
                });

            modelBuilder.Entity("ProyectoMancariBlue.Models.EstadoEmpleado", b =>
                {
                    b.Property<int>("IdEstadoEmpleado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idEstadoEmpleado");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("estado");

                    b.HasKey("IdEstadoEmpleado")
                        .HasName("PRIMARY");

                    b.ToTable("estado_empleado", (string)null);
                });

            modelBuilder.Entity("ProyectoMancariBlue.Models.RolEmpleado", b =>
                {
                    b.Property<int>("IdRolEmpleado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idRolEmpleado");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("rol");

                    b.HasKey("IdRolEmpleado")
                        .HasName("PRIMARY");

                    b.ToTable("rol_empleado", (string)null);
                });

            modelBuilder.Entity("ProyectoMancariBlue.Models.Empleado", b =>
                {
                    b.HasOne("ProyectoMancariBlue.Models.EstadoEmpleado", "IdEstadoEmpleadoNavigation")
                        .WithMany("Empleados")
                        .HasForeignKey("IdEstadoEmpleado")
                        .IsRequired()
                        .HasConstraintName("empleado_ibfk_1");

                    b.HasOne("ProyectoMancariBlue.Models.RolEmpleado", "IdRolEmpleadoNavigation")
                        .WithMany("Empleados")
                        .HasForeignKey("IdRolEmpleado")
                        .IsRequired()
                        .HasConstraintName("empleado_ibfk_2");

                    b.Navigation("IdEstadoEmpleadoNavigation");

                    b.Navigation("IdRolEmpleadoNavigation");
                });

            modelBuilder.Entity("ProyectoMancariBlue.Models.EstadoEmpleado", b =>
                {
                    b.Navigation("Empleados");
                });

            modelBuilder.Entity("ProyectoMancariBlue.Models.RolEmpleado", b =>
                {
                    b.Navigation("Empleados");
                });
#pragma warning restore 612, 618
        }
    }
}
